project:
  type: website
  output-dir: docs

website:
  title: "Sam Shanny-Csik"
  navbar:
    right:
      - href: index.qmd
        text: Home
      # - about.qmd
      # - href: resources.qmd
      #   text: Resources

format:
  html:
    theme: morph
    css: styles.css
    toc: true
    page-layout: full



